### ISSUE TITLE
positions.collateralBalances.balance is 0 for all collateral tokens

### ISSUE THREAD

**Issue by aroralanuk** [papercliplabs/compound-v3-subgraph#1]
Reproduce by querying: 

```graphql
positions(first: 10, orderBy: accounting__baseBalanceUsd, orderDirection: desc) {
    market {
      configuration {
        name
      }
    }
    account {
      address
      rewardsClaimed {
        amount
        amountUsd
      }
    }
    accounting {
      basePrincipal
      baseBalance
      baseTrackingIndex
      baseTrackingAccrued
      baseBalanceUsd
      collateralBalanceUsd
    }
    collateralBalances(first: 10, orderBy: balance, orderDirection: desc) {
      lastUpdateBlockNumber
      balance
      collateralToken {
        token {
          name
        }
        lastPriceUsd
      }
    }```

**Comment by spennyp** [comment]
@aroralanuk thanks for reporting this!

We will investigate and fix within the next few days.

As a heads up, this subgraph just got released to the public. Data validation and documentation cleanup is in progress, so we anticipate minor changes over this week.

**Comment by spennyp** [comment]
Hey @aroralanuk, after reviewing this, it does not appear to be an issue with the Subgraph.

Your query is sorting positions based on `baseBalanceUsd` and in `desc` direction.
This means you are getting the top 10 positions SUPPLYING to the market.

These positions are not borrowing anything, and as such they do not have any collateral supplied. 

If you change this query instead to the top 10 positions BORROWING (i.e negative baseBalance), by instead sorting `baseBalanceUsd` and in `asc` direction, you will see that the collateral balances are correctly being tracked. 

<img width="1162" alt="image" src="https://github.com/papercliplabs/compound-v3-subgraph/assets/31705429/428cc0b5-76b2-4c9c-9968-8acce81cf2ec">

Going to close this issue. 
Let me know if you have any other questions!

**Comment by aroralanuk** [comment]
Yes, that works perfectly, I was being dumb. Thanks a lot!
